# shellcheck shell=bash
# The container signing policy, written in ONE place
# (SPEC.md §spec:image-publication, §spec:os-updates, §spec:installer-media).
#
# Two consumers need the same answer and would otherwise each carry their own
# copy of it:
#
#   build_files/build.sh        bakes the policy into the published image
#   scripts/render-ignition.sh  places it on the machine DURING installation,
#                               so the very FIRST attachment is verified like
#                               every later update
#
# A disagreement between those two is not a build failure. It is a machine that
# installs itself and then refuses every update, or - worse - one that accepts
# an image nobody signed. Neither is visible from outside until it matters.
#
# Sourced, not executed. image.env must already be sourced by the caller.

# Where the repository's public signing key lives on a machine. The image ships
# it here and the installer places it here, so a policy generated by either
# refers to a file that exists.
KANTAINER_SIGNING_KEY_PATH=/etc/pki/containers/kantainer.pub

# The published image reference, lower-cased because a registry reference is.
# This is the ONE source of that string: the build bakes it into the policy, the
# publish workflow pushes to it, and the installer tells the machine to attach
# to it. If any two of those disagreed, the machine would look up a scope that
# is not in its policy.
kantainer_image_ref() {
    echo "${IMAGE_REGISTRY}/${REPO_ORGANIZATION}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]'
}

# The rule that accepts an image signed by this repository's key.
#
# matchRepository is required rather than stylistic: a cosign signature carries
# only a repository, so it is the only identity type that can accept one.
kantainer_policy_scope() {
    jq -n --arg key "${KANTAINER_SIGNING_KEY_PATH}" '
        [ { "type": "sigstoreSigned",
            "keyPath": $key,
            "signedIdentity": { "type": "matchRepository" } } ]'
}

# A complete policy.json, for a machine that has no policy of ours yet - which
# is every machine at install time, when it is still stock Fedora CoreOS.
#
# The docker transport default is set to reject alongside the top-level default,
# because it is consulted FIRST: a machine that inherited an accept-anything
# transport default would take an unsigned image regardless of what the
# top-level default says. With both set, a scope that ever stopped matching the
# published reference stops updates rather than accepting anything - the failure
# becomes loud instead of silent.
kantainer_policy_json() {
    local ref="$1" scope
    scope="$(kantainer_policy_scope)"
    jq -n --arg ref "${ref}" --argjson scope "${scope}" '
        { "default": [ { "type": "reject" } ],
          "transports": {
            "docker": {
              ($ref): $scope,
              "": [ { "type": "reject" } ]
            }
          }
        }'
}

# Tells containers/image to look for cosign signatures on our image. Without
# this the policy above finds no signature to check and refuses everything.
kantainer_registries_d_yaml() {
    local ref="$1"
    cat <<YAML
docker:
  ${ref}:
    use-sigstore-attachments: true
YAML
}
